const travelers=[{name:'Jen',icon:'🛍️',note:'Curious shops, coffee, kayaking, art, and beautiful detours.',priorities:['shopping','food','scenic','outdoors']},{name:'Blake',icon:'🍔',note:'Great food, low-stress scenery, house time, and friendly competition.',priorities:['food','games','scenic']},{name:'Porter',icon:'🎮',note:'Games, unusual stops, sweet treats, animals, and clear plans.',priorities:['games','food','shopping']},{name:'Mark',icon:'🚤',note:'Waterfront views, scenic drives, local history, and relaxed exploring.',priorities:['scenic','outdoors','food']},{name:'Nancy',icon:'🍒',note:'Shopping, gardens, handmade finds, scenic towns, and memorable meals.',priorities:['shopping','scenic','food']},{name:'Everyone',icon:'⚓',note:'Show the full family adventure menu.',priorities:[]}];
const activities=[{id:'suttons',title:'Wander Suttons Bay',category:'shopping',energy:'low',area:'Suttons Bay',icon:'🛍️',duration:'90 min',description:'A relaxed little-town browse with shops, art, snacks, and room for spontaneous treasure hunting.',people:['Jen','Nancy','Mark']},{id:'sleeping-bear',title:'Sleeping Bear Dunes Overlook',category:'outdoors',energy:'medium',area:'Glen Arbor',icon:'🌊',duration:'3 hrs',description:'The dramatic Lake Michigan view that earns a permanent spot in the family camera roll.',people:['Jen','Blake','Porter','Mark','Nancy']},{id:'cherry-stop',title:'The Great Cherry Taste Test',category:'food',energy:'low',area:'Traverse City',icon:'🍒',duration:'60 min',description:'Cherry salsa, soda, candy, and possibly one cherry product that should never have escaped the laboratory.',people:['Jen','Blake','Porter','Nancy']},{id:'kayak',title:'Morning Kayak on West Bay',category:'outdoors',energy:'high',area:'West Bay',icon:'🛶',duration:'90 min',description:'A calm early paddle before the day gets busy, with the house as home base.',people:['Jen','Porter','Mark']},{id:'bookshop',title:'Independent Bookstore Detour',category:'shopping',energy:'low',area:'Traverse City',icon:'📚',duration:'60 min',description:'A quiet browse with local books, gifts, and the very real possibility of leaving with a tote bag.',people:['Jen','Porter','Nancy']},{id:'shuffleboard',title:'Family Shuffleboard Championship',category:'games',energy:'low',area:'The House',icon:'🎯',duration:'90 min',description:'Official brackets, questionable officiating, and a trophy invented before the final.',people:['Blake','Porter','Mark']},{id:'peninsula-drive',title:'Old Mission Peninsula Scenic Drive',category:'scenic',energy:'low',area:'Old Mission Peninsula',icon:'🚗',duration:'3 hrs',description:'Water views, orchards, lighthouse energy, and stops whenever somebody says pull over.',people:['Blake','Mark','Nancy','Jen']},{id:'ice-cream',title:'Find the Best Ice Cream',category:'food',energy:'low',area:'Anywhere',icon:'🍦',duration:'45 min',description:'A rigorous family investigation conducted one scoop at a time.',people:['Porter','Blake','Nancy']},{id:'leland',title:'Explore Historic Fishtown',category:'scenic',energy:'medium',area:'Leland',icon:'⚓',duration:'2 hrs',description:'Weathered shanties, water, local shops, and Northern Michigan atmosphere turned all the way up.',people:['Jen','Mark','Nancy','Blake']}];
let selectedTraveler=localStorage.getItem('tcTraveler')||'Everyone';
let favorites=JSON.parse(localStorage.getItem('tcFavorites')||'[]');
let plan=JSON.parse(localStorage.getItem('tcPlan')||'{"morning":[],"afternoon":[],"evening":[]}');
const dialog=document.getElementById('travelerDialog');
const toast=document.getElementById('toast');
function showTab(name){document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===name));document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));
document.getElementById('enterApp').addEventListener('click',()=>{document.getElementById('landing').hidden=true;document.getElementById('appShell').hidden=false;showTab('home');});
function renderTravelers(){const markup=travelers.map(t=>`<button class="traveler-option" data-traveler="${t.name}"><span>${t.icon}</span><strong>${t.name}</strong><small>${t.note}</small></button>`).join('');document.getElementById('travelerGrid').innerHTML=markup;document.getElementById('travelerStrip').innerHTML=travelers.map(t=>`<button class="traveler-chip ${selectedTraveler===t.name?'active':''}" data-traveler="${t.name}">${t.icon} ${t.name}</button>`).join('');document.getElementById('profilePill').textContent=selectedTraveler==='Everyone'?'Choose traveler':`${selectedTraveler}'s view`;document.querySelectorAll('[data-traveler]').forEach(btn=>btn.addEventListener('click',()=>chooseTraveler(btn.dataset.traveler)));}
function chooseTraveler(name){selectedTraveler=name;localStorage.setItem('tcTraveler',name);renderTravelers();renderActivities();const t=travelers.find(x=>x.name===name);document.getElementById('personalizedMessage').textContent=name==='Everyone'?'Showing a little bit of everything for everyone.':`${name}'s view puts ${t.priorities.join(', ')} ideas near the front.`;if(dialog.open)dialog.close();showToast(`Welcome aboard, ${name}.`);}
function filteredActivities(){const q=document.getElementById('searchInput').value.toLowerCase().trim(),category=document.getElementById('categoryFilter').value,energy=document.getElementById('energyFilter').value,traveler=travelers.find(t=>t.name===selectedTraveler);return activities.filter(a=>category==='all'||a.category===category).filter(a=>energy==='all'||a.energy===energy).filter(a=>`${a.title} ${a.description} ${a.area}`.toLowerCase().includes(q)).sort((a,b)=>{if(selectedTraveler==='Everyone')return 0;const score=x=>(x.people.includes(selectedTraveler)?3:0)+(traveler.priorities.includes(x.category)?1:0);return score(b)-score(a);});}
function renderActivities(){document.getElementById('activityGrid').innerHTML=filteredActivities().map(a=>`<article class="activity-card"><button class="heart ${favorites.includes(a.id)?'active':''}" data-favorite="${a.id}" aria-label="Save ${a.title}">♥</button><div class="activity-image">${a.icon}</div><div class="activity-content"><div class="activity-meta"><span class="tag">${a.area}</span><span class="tag">${a.duration}</span></div><h3>${a.title}</h3><p>${a.description}</p></div></article>`).join('');document.querySelectorAll('[data-favorite]').forEach(btn=>btn.addEventListener('click',()=>toggleFavorite(btn.dataset.favorite)));}
function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem('tcFavorites',JSON.stringify(favorites));renderActivities();renderFavorites();renderPlanner();updateStats();showToast(favorites.includes(id)?'Saved to Family Favorites.':'Removed from favorites.');}
function renderFavorites(){const saved=activities.filter(a=>favorites.includes(a.id));document.getElementById('favoriteList').innerHTML=saved.length?saved.map(a=>`<article class="favorite-item"><strong>${a.icon} ${a.title}</strong><small>${a.area} · ${a.duration}</small></article>`).join(''):'<p>Nothing saved yet. Discover something delightful and tap the heart.</p>';}
function cardMarkup(a){return `<div class="planner-card" draggable="true" data-id="${a.id}"><strong>${a.icon} ${a.title}</strong><small>${a.area} · ${a.duration}</small></div>`;}
function renderPlanner(){const plannedIds=Object.values(plan).flat();const available=activities.filter(a=>favorites.includes(a.id)&&!plannedIds.includes(a.id));document.getElementById('plannerIdeas').innerHTML=available.length?available.map(cardMarkup).join(''):'<small>No unplanned favorites yet.</small>';['morning','afternoon','evening'].forEach(lane=>{document.getElementById(lane).innerHTML=plan[lane].map(id=>cardMarkup(activities.find(a=>a.id===id))).join('');});attachDrag();updateStats();}
function attachDrag(){document.querySelectorAll('.planner-card').forEach(card=>card.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',card.dataset.id)));document.querySelectorAll('.drop-zone').forEach(zone=>{zone.addEventListener('dragover',e=>{e.preventDefault();zone.classList.add('drag-over')});zone.addEventListener('dragleave',()=>zone.classList.remove('drag-over'));zone.addEventListener('drop',e=>{e.preventDefault();zone.classList.remove('drag-over');const id=e.dataTransfer.getData('text/plain');Object.keys(plan).forEach(k=>plan[k]=plan[k].filter(x=>x!==id));plan[zone.id].push(id);savePlan();});});document.getElementById('plannerIdeas').addEventListener('dragover',e=>e.preventDefault());document.getElementById('plannerIdeas').addEventListener('drop',e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');Object.keys(plan).forEach(k=>plan[k]=plan[k].filter(x=>x!==id));savePlan();});}
function savePlan(){localStorage.setItem('tcPlan',JSON.stringify(plan));renderPlanner();showToast('Day plan updated.');}
function updateStats(){document.getElementById('favoriteCount').textContent=favorites.length;document.getElementById('plannedCount').textContent=Object.values(plan).flat().length;}
function updateCountdown(){const diff=Math.max(0,new Date('2026-08-23T16:00:00')-new Date());document.getElementById('days').textContent=Math.floor(diff/86400000);document.getElementById('hours').textContent=Math.floor(diff%86400000/3600000);document.getElementById('minutes').textContent=Math.floor(diff%3600000/60000);}
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2200);}
document.getElementById('profilePill').addEventListener('click',()=>dialog.showModal());document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());document.getElementById('clearPlan').addEventListener('click',()=>{plan={morning:[],afternoon:[],evening:[]};savePlan();});['searchInput','categoryFilter','energyFilter'].forEach(id=>document.getElementById(id).addEventListener('input',renderActivities));renderTravelers();renderActivities();renderFavorites();renderPlanner();updateStats();updateCountdown();setInterval(updateCountdown,60000);