const travelers=[
{name:'Parker',icon:'🛍️',note:'Shops, coffee, art, pasta, waterfront wandering.'},
{name:'Blake',icon:'🍔',note:'Burgers, records, foodie finds, scenery, easy parking.'},
{name:'Porter',icon:'🎮',note:'Comics, games, cards, clear plans, sweets, unusual stops.'},
{name:'Mark',icon:'🚤',note:'Water views, local favorites, relaxed exploring.'},
{name:'Nancy',icon:'🍒',note:'Boutiques, handmade finds, scenic towns, memorable meals.'},
{name:'Everyone',icon:'⚓',note:'Show the full family shortlist.'}
];

const restaurants=[
{id:'west-end',name:'West End Tavern',town:'Traverse City',area:'Traverse City / West Bay',price:'$$',icon:'🌊',url:'https://www.westendtaverntc.com/',tags:['waterfront','burgers','patio','family','local-favorite'],fit:['Blake','Mark','Nancy','Parker'],summary:'A polished but comfortable West Bay option with broad appeal and a real water view.',menu:'Burgers, pizzas, steaks, fresh fish and comforting entrées.'},
{id:'slabtown',name:'Slabtown Burgers',town:'Traverse City',area:'Traverse City / West Side',price:'$',icon:'🍔',url:'https://www.slabtownburgers.com/',tags:['burgers','quick','family','local-favorite','hidden-gem'],fit:['Blake','Porter','Parker'],summary:'Casual hand-pattied burgers with patio seating and almost no ceremony.',menu:'Burgers, fries, wraps, salads and chicken sandwiches.'},
{id:'lil-bo',name:'Lil Bo',town:'Traverse City',area:'Traverse City / East Side',price:'$$',icon:'🕵️',url:'https://www.lilbotc.com/',tags:['burgers','hidden-gem','local-favorite','quick'],fit:['Blake','Parker','Mark'],summary:'A tiny neighborhood bar with old-school Traverse City character and playful burgers.',menu:'Olive burger, Cowboy Kicker, cheese curds and sandwiches.'},
{id:'modern-bird',name:'Modern Bird',town:'Traverse City',area:'Traverse City / Downtown',price:'$$$',icon:'✨',url:'https://modernbirdtc.com/menu',tags:['special','hidden-gem','local-favorite'],fit:['Parker','Nancy','Mark'],summary:'Seasonal, chef-driven plates for the night when dinner itself is the activity.',menu:'Creative small plates, vegetables, meat and seafood entrées.'},
{id:'stella',name:'Trattoria Stella',town:'Traverse City',area:'Grand Traverse Commons',price:'$$$',icon:'🍝',url:'https://stellatc.com/menu',tags:['pasta','special','local-favorite','hidden-gem'],fit:['Parker','Nancy','Mark'],summary:'Atmospheric Italian inside the historic Grand Traverse Commons.',menu:'Housemade pasta, farm-to-table Italian dishes and extensive wine.'},
{id:'boones',name:"Boone's Prime Time Pub",town:'Suttons Bay',area:'Suttons Bay',price:'$$',icon:'🍔',url:'https://www.boonesprimetimepub.com/',tags:['burgers','family','patio','local-favorite'],fit:['Blake','Porter','Mark','Nancy'],summary:'Classic Up North pub energy with a rooftop deck and a menu built for a whole family.',menu:'Burgers, Great Lakes perch, steaks and fresh fish.'},
{id:'vi-grill',name:'V.I. Grill',town:'Suttons Bay',area:'Suttons Bay',price:'$$',icon:'📍',url:'https://www.vigrill.com/',tags:['burgers','pasta','local-favorite','family','hidden-gem'],fit:['Blake','Parker','Nancy','Porter'],summary:'A dependable Suttons Bay favorite with burgers and pasta specials.',menu:'Burgers, quesadillas and rotating pasta specials.'},
{id:'arts',name:"Art's Tavern",town:'Glen Arbor',area:'Glen Arbor',price:'$',icon:'🏕️',url:'https://artsglenarbor.com/lunch-dinner-menu/',tags:['burgers','local-favorite','hidden-gem','family','quick'],fit:['Blake','Porter','Mark','Parker'],summary:'The beloved Glen Arbor institution for tots, burgers, whitefish and local personality.',menu:'Burgers, wings, whitefish, perch and soup.'},
{id:'boonedocks',name:'Boonedocks',town:'Glen Arbor',area:'Glen Arbor',price:'$$',icon:'🌲',url:'https://www.boonedocksga.com/',tags:['burgers','family','patio','local-favorite'],fit:['Blake','Porter','Mark','Nancy'],summary:'A rustic, family-friendly stop close to Sleeping Bear Dunes.',menu:'Burgers, local whitefish, perch, sandwiches and salads.'},
{id:'cherry-public',name:'Cherry Public House',town:'Glen Arbor',area:'Glen Arbor',price:'$$',icon:'🍒',url:'https://www.cherryrepublic.com/cherry-public-house',tags:['burgers','family','patio','local-favorite'],fit:['Porter','Blake','Parker','Nancy'],summary:'Michigan flavor without a formal dinner.',menu:'Cherry burger, sliders, smoked whitefish dip and pretzels.'},
{id:'blu',name:'Blu',town:'Glen Arbor',area:'Glen Arbor / Lake Michigan',price:'$$$',icon:'🌅',url:'https://www.glenarborblu.com/menu',tags:['waterfront','special','pasta','patio'],fit:['Parker','Nancy','Mark'],summary:'Lakeside fine dining with Sleeping Bear Bay views.',menu:'Gnocchi, scallops, salmon, lamb and seasonal dishes.'},
{id:'upriver',name:'Upriver Pizza',town:'Leland',area:'Leland',price:'$$',icon:'🍕',url:'https://upriverpizza.com/menu/',tags:['burgers','pasta','family','hidden-gem','local-favorite'],fit:['Porter','Blake','Parker','Mark'],summary:'A casual Leland wildcard for pizza, pasta and a Thursday smash burger.',menu:'Pizza, pasta, smash burgers, doughnuts and cinnastix.'}
];

const shops=[
{id:'rpm-records',name:'RPM Records',town:'Traverse City',area:'Traverse City / South Side',type:'records',icon:'💿',url:'https://www.rpmrecordstc.com/',fit:['Blake','Porter'],summary:'New and used vinyl, CDs, tapes, turntables, stereo equipment and repairs.'},
{id:'eugenes-records',name:"Eugene's Record Co-op",town:'Traverse City',area:'Traverse City / Downtown',type:'records',icon:'🎵',url:'https://www.eugenesrecordcoop.com/',fit:['Blake','Porter'],summary:'A downtown co-op carrying vinyl, turntables, accessories and repairs.'},
{id:'top-comics',name:'Top Comics',town:'Traverse City',area:'Traverse City / South Side',type:'comics',icon:'💥',url:'https://www.thetopcomics.com/',fit:['Porter','Blake'],summary:'New issues, vintage comics, collected editions, figures and posters.'},
{id:'fun-factory',name:'Fun Factory TC',town:'Traverse City',area:'Traverse City / South Side',type:'games',icon:'🎲',url:'https://www.thefunfactorytc.com/',fit:['Porter','Blake'],summary:'Trading cards, board games, tabletop supplies, events and tournaments.'},
{id:'wilson',name:'Wilson Antiques',town:'Traverse City',area:'Traverse City / Downtown',type:'antiques',icon:'🕰️',url:'https://wilsonantiques.com/',fit:['Parker','Nancy'],summary:'Four floors packed with antiques, vintage finds and wonderfully strange treasures.'},
{id:'horizon',name:'Horizon Books',town:'Traverse City',area:'Traverse City / Downtown',type:'books',icon:'📚',url:'https://www.horizonbooks.com/',fit:['Parker','Porter','Nancy'],summary:'A long-loved independent bookstore downtown.'},
{id:'tinker-studio',name:'Tinker Studio',town:'Traverse City',area:'Old Mission Peninsula',type:'art',icon:'🎨',url:'https://tinkerstudio.com/',fit:['Parker','Nancy'],summary:'Local pottery, jewelry, felt flowers, cards and functional art.'},
{id:'secret-stash',name:'My Secret Stash',town:'Traverse City',area:'Traverse City / Downtown',type:'art',icon:'🪩',url:'https://www.mysecretstash.com/',fit:['Parker','Nancy','Porter'],summary:'Michigan makers, local art, leather goods, apparel and gifts.'},
{id:'laughing-fish',name:'Laughing Fish Gallery',town:'Traverse City',area:'Grand Traverse Commons',type:'art',icon:'🐟',url:'https://www.laughingfishgallery.com/',fit:['Parker','Porter','Nancy'],summary:'Whimsical wooden fish art and paint-your-own projects.'},
{id:'sanctuary-goods',name:'Sanctuary Goods',town:'Traverse City',area:'Grand Traverse Commons',type:'art',icon:'🌿',url:'https://sanctuarygoods.com/',fit:['Parker','Nancy'],summary:'Nature-inspired artisan goods, jewelry, fine art and home accents.'},
{id:'m22-tc',name:'M22 Traverse City',town:'Traverse City',area:'Traverse City / Downtown',type:'gifts',icon:'🌊',url:'https://m22.com/',fit:['Parker','Nancy','Mark'],summary:'Northern Michigan apparel and gifts.'},
{id:'cherry-republic-tc',name:'Cherry Republic',town:'Traverse City',area:'Traverse City / Downtown',type:'food',icon:'🍒',url:'https://www.cherryrepublic.com/',fit:['Porter','Parker','Nancy'],summary:'Cherry salsa, candy, preserves, drinks and gifts.'},
{id:'m22-sb',name:'M22 Suttons Bay',town:'Suttons Bay',area:'Suttons Bay',type:'gifts',icon:'🧢',url:'https://m22.com/',fit:['Mark','Nancy','Parker'],summary:'Up North apparel and gifts on St. Joseph Street.'},
{id:'nykamping',name:'Nykamping',town:'Suttons Bay',area:'Suttons Bay',type:'boutique',icon:'🧵',url:'https://nykamping.com/',fit:['Parker','Nancy'],summary:'Handmade apparel and selected pre-loved textiles.'},
{id:'benjamin-maier',name:'Benjamin Maier Ceramics',town:'Leland',area:'Leland',type:'art',icon:'🏺',url:'https://benjaminmaierceramics.com/',fit:['Parker','Nancy'],summary:'Elevated handmade ceramics with a northern Michigan soul.'},
{id:'cottage-book',name:'The Cottage Book Shop',town:'Glen Arbor',area:'Glen Arbor',type:'books',icon:'📖',url:'https://www.cottagebooks.com/',fit:['Parker','Porter','Nancy'],summary:'A cozy independent bookstore perfect for a Sleeping Bear day.'},
{id:'cherry-republic-ga',name:'Cherry Republic Glen Arbor',town:'Glen Arbor',area:'Glen Arbor',type:'food',icon:'🍒',url:'https://www.cherryrepublic.com/',fit:['Porter','Parker','Nancy'],summary:'The full cherry wonderland with samples, food and gifts.'},
{id:'fishtown',name:'Fishtown Shops',town:'Leland',area:'Leland / Fishtown',type:'art',icon:'🎣',url:'https://www.fishtownmi.org/',fit:['Parker','Nancy','Mark'],summary:'Shanty shops, art, food and waterfront atmosphere.'}
];

const activities=[
{id:'house-water',name:'West Bay Water Day',town:'At the House',area:'At the House',type:'beach',icon:'🛶',url:'#',tags:['dog-friendly','free','low-energy','water','scenic'],fit:['Everyone'],dog:'Yes, at the house',summary:'Kayak, swim, lounge on the dock, use the hot tub and let the house itself be the destination.'},
{id:'clinch-park',name:'Clinch Park & TART Trail',town:'Traverse City',area:'Traverse City / Downtown',type:'beach',icon:'🏖️',url:'https://www.traversecitymi.gov/community/recreation-directory/clinch-park-beach/clinch-park.html',tags:['dog-friendly','free','low-energy','water','scenic'],fit:['Parker','Mark','Nancy'],dog:'Leashed dogs in the park, not on the beach',summary:'Bayfront park, marina, splash pad, swimming and an easy trail connection through downtown.'},
{id:'commons-trails',name:'Grand Traverse Commons Trails',town:'Traverse City',area:'Grand Traverse Commons',type:'hike',icon:'🌳',url:'https://www.thevillagetc.com/',tags:['dog-friendly','free','active','scenic'],fit:['Parker','Blake','Porter'],dog:'Leashed dogs welcome outdoors',summary:'Wooded trails and historic grounds that pair naturally with Stella, Laughing Fish and Sanctuary Goods.'},
{id:'old-mission-drive',name:'Old Mission Peninsula Scenic Loop',town:'Old Mission Peninsula',area:'Old Mission Peninsula',type:'scenic',icon:'🚗',url:'https://www.traversecity.com/plan/trip-ideas/old-mission-peninsula/',tags:['dog-friendly','low-energy','scenic'],fit:['Everyone'],dog:'Dogs can join the drive and outdoor stops; verify individual venues',summary:'A low-stress scenic drive with bay overlooks, farm stands, vineyards and lighthouse country.'},
{id:'mission-point',name:'Mission Point Lighthouse',town:'Old Mission Peninsula',area:'Old Mission Peninsula',type:'history',icon:'🔦',url:'https://www.missionpointlighthouse.com/',tags:['dog-friendly','free','low-energy','scenic'],fit:['Mark','Nancy','Parker'],dog:'Leashed dogs on surrounding grounds and trails; not inside buildings',summary:'A photogenic lighthouse stop at the tip of Old Mission Peninsula with nearby trails and shoreline.'},
{id:'suttons-bay-walk',name:'Suttons Bay Village & Beach Walk',town:'Suttons Bay',area:'Suttons Bay',type:'relax',icon:'⛵',url:'https://www.suttonsbayarea.com/',tags:['dog-friendly','free','low-energy','scenic'],fit:['Everyone'],dog:'Leashed dogs outdoors; individual shops vary',summary:'A compact village day combining waterfront wandering, shops, lunch and almost no backtracking.'},
{id:'fishtown-walk',name:'Fishtown & Leland Harbor',town:'Leland',area:'Leland / Fishtown',type:'history',icon:'🎣',url:'https://www.fishtownmi.org/',tags:['dog-friendly','free','low-energy','water','scenic'],fit:['Everyone'],dog:'Leashed dogs outdoors; individual shops vary',summary:'Historic fishing shanties, harbor views, smoked fish and compact shopping.'},
{id:'empire-bluff',name:'Empire Bluff Trail',town:'Empire / Sleeping Bear',area:'Empire / Sleeping Bear',type:'hike',icon:'🥾',url:'https://www.nps.gov/slbe/planyourvisit/trails.htm',tags:['dog-friendly','active','scenic'],fit:['Parker','Mark','Blake'],dog:'Leashed dogs allowed year-round',summary:'A classic overlook hike with a major Lake Michigan payoff.'},
{id:'pyramid-point',name:'Pyramid Point Trail',town:'Empire / Sleeping Bear',area:'Glen Arbor / Sleeping Bear',type:'hike',icon:'⛰️',url:'https://www.nps.gov/slbe/planyourvisit/trails.htm',tags:['dog-friendly','active','scenic'],fit:['Parker','Mark','Blake'],dog:'Leashed dogs allowed year-round',summary:'A scenic trail north of Glen Arbor that pairs well with a Glen Arbor meal and shops.'},
{id:'dune-climb',name:'Dune Climb',town:'Empire / Sleeping Bear',area:'Empire / Sleeping Bear',type:'family',icon:'🏜️',url:'https://www.nps.gov/places/000/dune-center.htm',tags:['active','scenic'],fit:['Porter','Blake','Mark'],dog:'No pets on the Dune Climb or at the Dune Center',summary:'The iconic sand climb. Best early or late for cooler temperatures and easier parking.'},
{id:'pierce-stocking',name:'Pierce Stocking Scenic Drive',town:'Empire / Sleeping Bear',area:'Empire / Sleeping Bear',type:'scenic',icon:'📸',url:'https://www.nps.gov/slbe/planyourvisit/index.htm',tags:['dog-friendly','low-energy','scenic'],fit:['Everyone'],dog:'Dogs may join at permitted outdoor stops; keep leashed and follow posted restrictions',summary:'A scenic driving loop with overlooks that delivers Sleeping Bear drama without requiring a long hike.'},
{id:'rainy-commons',name:'Commons Art & History Loop',town:'Traverse City',area:'Grand Traverse Commons',type:'history',icon:'☔',url:'https://www.thevillagetc.com/',tags:['rainy-day','low-energy'],fit:['Parker','Porter','Nancy'],dog:'Mostly an indoor plan, so dogs would stay home',summary:'Bundle the Commons galleries, shops, architecture and an early Stella meal into one weather-proof block.'}
];

const houseGalleryData=[
{id:'exterior',title:'Exterior, yard and waterfront',kicker:'Welcome home',description:'The house sits directly on West Bay with a broad lawn, shoreline, dock, porch and several outdoor gathering spots.',images:['IMG_9768.jpeg','IMG_9769.jpeg','IMG_9770.jpeg','IMG_9788.jpeg','IMG_9789.jpeg','IMG_9792.jpeg','IMG_9793.jpeg','IMG_9795.jpeg','IMG_9796.jpeg','IMG_9797.jpeg','IMG_9798.jpeg','IMG_9799.jpeg','IMG_9800.jpeg','IMG_9814.jpeg']},
{id:'game-room',title:'Garage game room',kicker:'Rainy-day headquarters',description:'Shuffleboard, television, seating and a wide-open view toward the bay make this the second family living room.',images:['IMG_9771.jpeg','IMG_9782.jpeg']},
{id:'kitchen-living',title:'Kitchen, dining and living spaces',kicker:'The gathering zone',description:'Quartz counters, stainless appliances, a long island, dining space and comfortable living areas.',images:['IMG_9775.jpeg','IMG_9777.jpeg','IMG_9778.jpeg','IMG_9779.jpeg','IMG_9783.jpeg','IMG_9785.jpeg','IMG_9786.jpeg']},
{id:'bathrooms',title:'Bathrooms',kicker:'Two full baths',description:'One tub-or-shower bath and one shower-only bath.',images:['IMG_9784.jpeg','IMG_9791.jpeg']},
{id:'bedrooms',title:'Queen bedrooms',kicker:'Sleep spaces',description:'The property has three queen bedrooms. These are the available listing photographs.',images:['IMG_9780.jpeg','IMG_9787.jpeg','IMG_9790.jpeg']},
{id:'patio-hot-tub',title:'Patio, hot tub and outdoor hangouts',kicker:'After the day trip',description:'The seven-person hot tub, backyard, patio and outdoor seating offer several ways to end the day.',images:['IMG_9794.jpeg','IMG_9795.jpeg','IMG_9796.jpeg']},
{id:'maps',title:'Maps and location',kicker:'Where we are',description:'On West Bay along M-22, roughly six miles north of Traverse City and 7.5 miles south of Suttons Bay.',images:['IMG_9806.png','IMG_9807.jpeg','IMG_9815.png']}
];

const tripDays=[
{id:'sun23',label:'Sun 23',date:'Sunday · August 23',title:'Arrival Day'},
{id:'mon24',label:'Mon 24',date:'Monday · August 24',title:'First Full Day'},
{id:'tue25',label:'Tue 25',date:'Tuesday · August 25',title:'Adventure Day'},
{id:'wed26',label:'Wed 26',date:'Wednesday · August 26',title:'Choose Our Favorite'},
{id:'thu27',label:'Thu 27',date:'Thursday · August 27',title:'Departure Day'}
];
const allPlaces=[...restaurants.map(x=>({...x,kind:'restaurant'})),...shops.map(x=>({...x,kind:'shop',price:'',tags:[x.type]})),...activities.map(x=>({...x,kind:'activity',price:'',tags:x.tags||[]}))];
let selectedTraveler=localStorage.getItem('tcTraveler')||'Everyone';
if(selectedTraveler==='Jen'){selectedTraveler='Parker';localStorage.setItem('tcTraveler','Parker');}
let favorites=JSON.parse(localStorage.getItem('tcFavoritesV3')||localStorage.getItem('tcFavoritesV2')||'[]');
let plan=loadPlan();
let activeDay=localStorage.getItem('tcActiveDay')||'sun23';
let activeRestaurantTags=[];
let activeActivityTags=[];
const dialog=document.getElementById('travelerDialog');
const toast=document.getElementById('toast');

function emptyDay(){return {morning:[],afternoon:[],evening:[]};}
function loadPlan(){
  const saved=localStorage.getItem('tcPlanV3');
  if(saved)return JSON.parse(saved);
  const old=JSON.parse(localStorage.getItem('tcPlanV2')||'null');
  return {sun23:emptyDay(),mon24:old||emptyDay(),tue25:emptyDay(),wed26:emptyDay(),thu27:emptyDay()};
}
function showTab(name){document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===name));document.querySelectorAll('.bottom-nav [data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));
document.getElementById('enterApp').onclick=()=>{document.getElementById('landing').hidden=true;document.getElementById('appShell').hidden=false;showTab('home');};

function renderTravelers(){
  document.getElementById('travelerGrid').innerHTML=travelers.map(t=>`<button class="traveler-option" data-traveler="${t.name}"><span>${t.icon}</span><strong>${t.name}</strong><small>${t.note}</small></button>`).join('');
  document.getElementById('travelerStrip').innerHTML=travelers.map(t=>`<button class="traveler-chip ${selectedTraveler===t.name?'active':''}" data-traveler="${t.name}">${t.icon} ${t.name}</button>`).join('');
  document.getElementById('profilePill').textContent=selectedTraveler==='Everyone'?'Choose traveler':`${selectedTraveler}'s view`;
  document.querySelectorAll('[data-traveler]').forEach(btn=>btn.onclick=()=>chooseTraveler(btn.dataset.traveler));
}
function chooseTraveler(name){selectedTraveler=name;localStorage.setItem('tcTraveler',name);renderTravelers();renderRestaurants();renderShops();renderActivities();if(dialog.open)dialog.close();showToast(name==='Everyone'?'Showing choices for everyone.':`Showing stronger matches for ${name}.`);}
function typeLabel(p){return p.kind==='restaurant'?'Restaurant':p.kind==='shop'?'Shopping':'Activity';}
function placeCard(p){
  const saved=favorites.includes(p.id),fits=selectedTraveler!=='Everyone'&&(p.fit||[]).includes(selectedTraveler);
  const tags=(p.tags||[p.type]).slice(0,6).map(t=>`<span class="tag">${t.replaceAll('-',' ')}</span>`).join('');
  const dog=p.kind==='activity'?`<div class="dog-status ${p.tags.includes('dog-friendly')?'yes':'no'}">🐾 ${p.dog}</div>`:'';
  return `<article class="place-card kind-${p.kind}"><div class="card-type">${typeLabel(p)}</div><div class="icon-badge">${p.icon}</div><h3>${p.name}</h3><div class="place-sub">📍 ${p.area}${p.price?` · ${p.price}`:''}${fits?' · Strong match':''}</div><p>${p.summary}</p>${dog}<div class="tag-row">${tags}</div>${p.menu?`<div class="menu-examples"><strong>Menu examples:</strong> ${p.menu}</div>`:''}<div class="card-actions">${p.url==='#'?'':`<a href="${p.url}" target="_blank" rel="noopener">Official info ↗</a>`}<button class="save-place ${saved?'active':''}" data-save="${p.id}">${saved?'♥ Saved':'♡ Save'}</button></div></article>`;
}
function attachSaveButtons(){document.querySelectorAll('[data-save]').forEach(btn=>btn.onclick=()=>toggleFavorite(btn.dataset.save));}
function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem('tcFavoritesV3',JSON.stringify(favorites));renderRestaurants();renderShops();renderActivities();renderPlanner();updateStats();showToast(favorites.includes(id)?'Saved to the family shortlist.':'Removed from saved places.');}
function renderRestaurants(){const q=restaurantSearch.value.toLowerCase().trim(),town=restaurantTown.value,price=restaurantPrice.value;let results=restaurants.filter(r=>town==='all'||r.town===town).filter(r=>price==='all'||r.price===price).filter(r=>activeRestaurantTags.every(t=>r.tags.includes(t))).filter(r=>`${r.name} ${r.area} ${r.summary} ${r.menu} ${r.tags.join(' ')}`.toLowerCase().includes(q));if(selectedTraveler!=='Everyone')results.sort((a,b)=>Number(b.fit.includes(selectedTraveler))-Number(a.fit.includes(selectedTraveler)));restaurantResultsNote.textContent=`${results.length} restaurant${results.length===1?'':'s'} match.`;restaurantGrid.innerHTML=results.map(placeCard).join('')||'<p>No exact matches. Remove one filter and try again.</p>';attachSaveButtons();}
function renderShops(){const q=shopSearch.value.toLowerCase().trim(),town=shopTown.value,type=shopType.value;let results=shops.filter(s=>town==='all'||s.town===town).filter(s=>type==='all'||s.type===type).filter(s=>`${s.name} ${s.area} ${s.type} ${s.summary}`.toLowerCase().includes(q));if(selectedTraveler!=='Everyone')results.sort((a,b)=>Number((b.fit||[]).includes(selectedTraveler))-Number((a.fit||[]).includes(selectedTraveler)));shopGrid.innerHTML=results.map(placeCard).join('')||'<p>No matches yet. Try another area or category.</p>';attachSaveButtons();}
function renderActivityChips(){document.querySelectorAll('#activityChips button').forEach(b=>b.classList.toggle('active',activeActivityTags.includes(b.dataset.tag)));}
function renderActivities(){const q=activitySearch.value.toLowerCase().trim(),town=activityTown.value,type=activityType.value;let results=activities.filter(a=>town==='all'||a.town===town).filter(a=>type==='all'||a.type===type).filter(a=>activeActivityTags.every(t=>a.tags.includes(t))).filter(a=>`${a.name} ${a.area} ${a.summary} ${a.tags.join(' ')}`.toLowerCase().includes(q));activityResultsNote.textContent=`${results.length} activit${results.length===1?'y':'ies'} match.`;activityGrid.innerHTML=results.map(placeCard).join('')||'<p>No exact matches. Try removing one filter.</p>';attachSaveButtons();}

function plannerCard(p,inPlan=false){return `<div class="planner-card kind-${p.kind}" draggable="true" data-id="${p.id}"><div><strong>${p.icon} ${p.name}</strong><small>📍 ${p.area} · ${typeLabel(p)}</small></div>${inPlan?'<button class="remove-stop" aria-label="Remove">×</button>':`<div class="quick-add"><button data-add="morning">AM</button><button data-add="afternoon">PM</button><button data-add="evening">EVE</button></div>`}</div>`;}
function renderDayTabs(){dayTabs.innerHTML=tripDays.map(d=>`<button class="day-tab ${activeDay===d.id?'active':''}" data-day="${d.id}"><strong>${d.label}</strong><small>${Object.values(plan[d.id]).flat().length} stops</small></button>`).join('');document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{activeDay=b.dataset.day;localStorage.setItem('tcActiveDay',activeDay);renderPlanner();});}
function renderPlanner(){
  renderDayTabs();
  const day=tripDays.find(d=>d.id===activeDay),dayPlan=plan[activeDay],plannedAll=Object.values(plan).flatMap(d=>Object.values(d).flat());
  activeDayDate.textContent=day.date;activeDayTitle.textContent=day.title;
  const available=allPlaces.filter(p=>favorites.includes(p.id)&&!plannedAll.includes(p.id));
  plannerIdeas.innerHTML=available.length?available.map(p=>plannerCard(p)).join(''):'<small>Save activities, restaurants, or shops to fill this tray.</small>';
  ['morning','afternoon','evening'].forEach(slot=>{const zone=document.getElementById(slot);zone.innerHTML=dayPlan[slot].map(id=>allPlaces.find(p=>p.id===id)).filter(Boolean).map(p=>plannerCard(p,true)).join('')||'<small class="empty-slot">Drop or add something here.</small>';zone.querySelectorAll('.planner-card').forEach(card=>card.querySelector('.remove-stop').onclick=()=>removeFromPlan(card.dataset.id));});
  plannerIdeas.querySelectorAll('.planner-card').forEach(card=>{card.querySelectorAll('[data-add]').forEach(btn=>btn.onclick=()=>addToPlan(card.dataset.id,btn.dataset.add));});
  attachDrag();renderRouteAdvice();updateStats();
}
function addToPlan(id,slot){Object.values(plan).forEach(day=>Object.keys(day).forEach(k=>day[k]=day[k].filter(x=>x!==id)));plan[activeDay][slot].push(id);savePlan();}
function removeFromPlan(id){Object.keys(plan[activeDay]).forEach(k=>plan[activeDay][k]=plan[activeDay][k].filter(x=>x!==id));savePlan();}
function attachDrag(){document.querySelectorAll('.planner-card').forEach(card=>card.ondragstart=e=>e.dataTransfer.setData('text/plain',card.dataset.id));document.querySelectorAll('.drop-zone').forEach(zone=>{zone.ondragover=e=>{e.preventDefault();zone.classList.add('drag-over')};zone.ondragleave=()=>zone.classList.remove('drag-over');zone.ondrop=e=>{e.preventDefault();zone.classList.remove('drag-over');addToPlan(e.dataTransfer.getData('text/plain'),zone.id);};});}
function savePlan(){localStorage.setItem('tcPlanV3',JSON.stringify(plan));renderPlanner();showToast('Trip plan updated.');}
function renderRouteAdvice(){const ids=Object.values(plan[activeDay]).flat(),places=ids.map(id=>allPlaces.find(p=>p.id===id)).filter(Boolean),areas=[...new Set(places.map(p=>p.area))];if(!places.length){routeAdvice.innerHTML='<strong>Route helper:</strong> Add a few stops and I’ll flag whether the day is geographically tidy.';return;}if(areas.length<=2){routeAdvice.innerHTML=`<strong>Nice cluster:</strong> This day stays mostly around ${areas.join(' and ')}.`;}else{routeAdvice.innerHTML=`<strong>Windshield warning:</strong> This day spans ${areas.length} areas: ${areas.join(', ')}. Consider moving one cluster to another day.`;}}
function updateStats(){favoriteCount.textContent=favorites.length;plannedCount.textContent=Object.values(plan).flatMap(d=>Object.values(d).flat()).length;}
function updateCountdown(){const diff=Math.max(0,new Date('2026-08-23T16:00:00')-new Date());days.textContent=Math.floor(diff/86400000);hours.textContent=Math.floor(diff%86400000/3600000);minutes.textContent=Math.floor(diff%3600000/60000);}
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2300);}
function renderHouseGalleries(){const root=houseGalleries;root.innerHTML=houseGalleryData.map(g=>`<section class="gallery-section" data-gallery="${g.id}" data-index="0"><div class="gallery-head"><div><p class="eyebrow dark">${g.kicker}</p><h3>${g.title}</h3><p>${g.description}</p></div><span class="gallery-count">1 / ${g.images.length}</span></div><div class="gallery-stage"><img src="Assets/Assets/Images/${g.images[0]}" alt="${g.title} photo 1" data-open-photo><button class="gallery-control prev">‹</button><button class="gallery-control next">›</button><div class="gallery-caption"><strong>${g.title}</strong><small>Swipe or use arrows</small></div></div><div class="gallery-thumbs">${g.images.map((img,i)=>`<button class="gallery-thumb ${i===0?'active':''}" data-thumb="${i}"><img src="Assets/Assets/Images/${img}" alt=""></button>`).join('')}</div></section>`).join('');root.querySelectorAll('.gallery-section').forEach(section=>{const gallery=houseGalleryData.find(g=>g.id===section.dataset.gallery),stage=section.querySelector('.gallery-stage');const update=n=>{const i=(n+gallery.images.length)%gallery.images.length;section.dataset.index=i;stage.querySelector('img').src=`Assets/Assets/Images/${gallery.images[i]}`;section.querySelector('.gallery-count').textContent=`${i+1} / ${gallery.images.length}`;section.querySelectorAll('.gallery-thumb').forEach((t,j)=>t.classList.toggle('active',j===i));};section.querySelector('.prev').onclick=()=>update(Number(section.dataset.index)-1);section.querySelector('.next').onclick=()=>update(Number(section.dataset.index)+1);section.querySelectorAll('[data-thumb]').forEach(b=>b.onclick=()=>update(Number(b.dataset.thumb)));let startX=0;stage.ontouchstart=e=>startX=e.changedTouches[0].clientX;stage.ontouchend=e=>{const d=e.changedTouches[0].clientX-startX;if(Math.abs(d)>45)update(Number(section.dataset.index)+(d<0?1:-1));};stage.querySelector('[data-open-photo]').onclick=()=>openPhoto(gallery,Number(section.dataset.index));});}
function openPhoto(gallery,index){dialogPhoto.src=`Assets/Assets/Images/${gallery.images[index]}`;dialogCaption.textContent=`${gallery.title} · photo ${index+1} of ${gallery.images.length}`;photoDialog.showModal();}

profilePill.onclick=()=>dialog.showModal();document.querySelector('#travelerDialog .dialog-close').onclick=()=>dialog.close();document.querySelector('.photo-close').onclick=()=>photoDialog.close();clearPlan.onclick=()=>{plan[activeDay]=emptyDay();savePlan();};
['restaurantSearch','restaurantTown','restaurantPrice'].forEach(id=>document.getElementById(id).addEventListener('input',renderRestaurants));
['shopSearch','shopTown','shopType'].forEach(id=>document.getElementById(id).addEventListener('input',renderShops));
['activitySearch','activityTown','activityType'].forEach(id=>document.getElementById(id).addEventListener('input',renderActivities));
document.querySelectorAll('#restaurantChips button').forEach(btn=>btn.onclick=()=>{const t=btn.dataset.tag;activeRestaurantTags=activeRestaurantTags.includes(t)?activeRestaurantTags.filter(x=>x!==t):[...activeRestaurantTags,t];btn.classList.toggle('active');renderRestaurants();});
document.querySelectorAll('#activityChips button').forEach(btn=>btn.onclick=()=>{const t=btn.dataset.tag;activeActivityTags=activeActivityTags.includes(t)?activeActivityTags.filter(x=>x!==t):[...activeActivityTags,t];renderActivityChips();renderActivities();});
renderTravelers();renderRestaurants();renderShops();renderActivityChips();renderActivities();renderPlanner();renderHouseGalleries();updateStats();updateCountdown();setInterval(updateCountdown,60000);