const travelers=[
{name:'Parker',icon:'🛍️',note:'Shops, coffee, art, pasta, waterfront wandering.'},
{name:'Blake',icon:'🍔',note:'Burgers, records, low-stress meals, scenery, easy parking.'},
{name:'Porter',icon:'🎮',note:'Comics, games, cards, clear plans, sweets, unusual stops.'},
{name:'Mark',icon:'🚤',note:'Water views, local favorites, relaxed exploring.'},
{name:'Nancy',icon:'🍒',note:'Boutiques, handmade finds, scenic towns, memorable meals.'},
{name:'Everyone',icon:'⚓',note:'Show the full family shortlist.'}
];

const restaurants=[
{id:'west-end',name:'West End Tavern',town:'Traverse City',price:'$$',icon:'🌊',url:'https://www.westendtaverntc.com/',tags:['waterfront','burgers','patio','family','local-favorite'],fit:['Blake','Mark','Nancy','Parker'],summary:'A polished but comfortable West Bay option with broad appeal and a real water view.',menu:'Gourmet burgers, artisan pizzas, steaks, fresh fish, comforting entrées.'},
{id:'slabtown',name:'Slabtown Burgers',town:'Traverse City',price:'$',icon:'🍔',url:'https://www.slabtownburgers.com/',tags:['burgers','quick','family','local-favorite','hidden-gem'],fit:['Blake','Porter','Parker'],summary:'Casual, homemade, hand-pattied burgers with patio seating and almost no ceremony.',menu:'Burgers, fries, soups, wraps, salads, hot dogs, chicken sandwiches, veggie burgers.'},
{id:'lil-bo',name:'Lil Bo',town:'Traverse City',price:'$$',icon:'🕵️',url:'https://www.lilbotc.com/',tags:['burgers','hidden-gem','local-favorite','quick'],fit:['Blake','Parker','Mark'],summary:'A tiny neighborhood bar with old-school Traverse City character and playful burgers.',menu:'Olive burger, Cowboy Kicker, Smurf & Turf, cheese curds, sandwiches.'},
{id:'modern-bird',name:'Modern Bird',town:'Traverse City',price:'$$$',icon:'✨',url:'https://modernbirdtc.com/menu',tags:['special','hidden-gem','local-favorite'],fit:['Parker','Nancy','Mark'],summary:'Seasonal, chef-driven plates for the night when dinner itself is the activity.',menu:'Seasonal vegetables, breads, creative small plates, meat and seafood entrées.'},
{id:'stella',name:'Trattoria Stella',town:'Traverse City',price:'$$$',icon:'🍝',url:'https://stellatc.com/menu',tags:['pasta','special','local-favorite','hidden-gem'],fit:['Parker','Nancy','Mark'],summary:'Atmospheric Italian inside the historic Grand Traverse Commons. Reservations are the smart move.',menu:'Burrata, housemade pasta, rotating farm-to-table Italian dishes, extensive wine.'},
{id:'boones',name:"Boone's Prime Time Pub",town:'Suttons Bay',price:'$$',icon:'🍔',url:'https://www.boonesprimetimepub.com/',tags:['burgers','family','patio','local-favorite'],fit:['Blake','Porter','Mark','Nancy'],summary:'Classic Up North pub energy with a rooftop deck and a menu built to keep a whole family happy.',menu:'M22 Burger, Great Lakes perch basket, steaks, fresh fish.'},
{id:'vi-grill',name:'V.I. Grill',town:'Suttons Bay',price:'$$',icon:'📍',url:'https://www.vigrill.com/',tags:['burgers','pasta','local-favorite','family','hidden-gem'],fit:['Blake','Parker','Nancy','Porter'],summary:'A dependable Suttons Bay local favorite with burgers and a Thursday pasta tradition.',menu:'Villager Burger, custom burgers, quesadillas and pasta specials.'},
{id:'arts',name:"Art's Tavern",town:'Glen Arbor',price:'$',icon:'🏕️',url:'https://artsglenarbor.com/lunch-dinner-menu/',tags:['burgers','local-favorite','hidden-gem','family','quick'],fit:['Blake','Porter','Mark','Parker'],summary:'The beloved Glen Arbor institution for tots, burgers, whitefish and local personality.',menu:'Burgers, wings, whitefish sandwich, perch and soup.'},
{id:'boonedocks',name:'Boonedocks',town:'Glen Arbor',price:'$$',icon:'🌲',url:'https://www.boonedocksga.com/',tags:['burgers','family','patio','local-favorite'],fit:['Blake','Porter','Mark','Nancy'],summary:'A rustic, family-friendly stop only a couple of miles from Sleeping Bear Dunes.',menu:'Burgers, local whitefish, perch, sandwiches and salads.'},
{id:'cherry-public',name:'Cherry Public House',town:'Glen Arbor',price:'$$',icon:'🍒',url:'https://www.cherryrepublic.com/cherry-public-house',tags:['burgers','family','patio','local-favorite'],fit:['Porter','Blake','Parker','Nancy'],summary:'A fun Glen Arbor stop when the family wants Michigan flavor without a formal dinner.',menu:'Cherry bacon marmalade burger, sliders, smoked whitefish dip and pretzels.'},
{id:'blu',name:'Blu',town:'Glen Arbor',price:'$$$',icon:'🌅',url:'https://www.glenarborblu.com/menu',tags:['waterfront','special','pasta','patio'],fit:['Parker','Nancy','Mark'],summary:'Lakeside fine dining with Sleeping Bear Bay views and a highly seasonal menu.',menu:'Gnocchi, scallops, wagyu, salmon, lamb and composed vegetable dishes.'},
{id:'upriver',name:'Upriver Pizza',town:'Leland',price:'$$',icon:'🍕',url:'https://upriverpizza.com/menu/',tags:['burgers','pasta','family','hidden-gem','local-favorite'],fit:['Porter','Blake','Parker','Mark'],summary:'A casual Leland-area wildcard for pizza, pasta and a Thursday smash burger.',menu:'Pizza, pasta, smash burgers, doughnuts and cinnastix.'}
];

const shops=[
{id:'rpm-records',name:'RPM Records',town:'Traverse City',type:'records',icon:'💿',url:'https://www.rpmrecordstc.com/',fit:['Blake','Porter'],summary:'New and used vinyl, CDs, tapes, turntables, stereo equipment and repair service.'},
{id:'eugenes-records',name:"Eugene's Record Co-op",town:'Traverse City',type:'records',icon:'🎵',url:'https://www.eugenesrecordcoop.com/',fit:['Blake','Porter'],summary:'A downtown co-op carrying new and used vinyl, turntables, accessories and repairs.'},
{id:'top-comics',name:'Top Comics',town:'Traverse City',type:'comics',icon:'💥',url:'https://www.thetopcomics.com/',fit:['Porter','Blake'],summary:'New issues, vintage comics, collected editions, figures, posters and collecting supplies.'},
{id:'fun-factory',name:'Fun Factory TC',town:'Traverse City',type:'games',icon:'🎲',url:'https://www.thefunfactorytc.com/',fit:['Porter','Blake'],summary:'Trading cards, board games, tabletop supplies, events and tournaments.'},
{id:'wilson',name:'Wilson Antiques',town:'Traverse City',type:'antiques',icon:'🕰️',url:'https://wilsonantiques.com/',fit:['Parker','Nancy'],summary:'Four floors packed with antiques, vintage finds and wonderfully strange treasures.'},
{id:'horizon',name:'Horizon Books',town:'Traverse City',type:'books',icon:'📚',url:'https://www.horizonbooks.com/',fit:['Parker','Porter','Nancy'],summary:'A long-loved independent bookstore downtown with books, gifts and plenty of browsing room.'},
{id:'tinker-studio',name:'Tinker Studio',town:'Traverse City',type:'art',icon:'🎨',url:'https://tinkerstudio.com/',fit:['Parker','Nancy'],summary:'Old Mission Peninsula studio representing dozens of local artists, with pottery, jewelry, felt flowers and cards.'},
{id:'secret-stash',name:'My Secret Stash',town:'Traverse City',type:'art',icon:'🪩',url:'https://www.mysecretstash.com/',fit:['Parker','Nancy','Porter'],summary:'Bohemian downtown boutique featuring Michigan makers, local art, leather goods, apparel and gifts.'},
{id:'laughing-fish',name:'Laughing Fish Gallery',town:'Traverse City',type:'art',icon:'🐟',url:'https://www.laughingfishgallery.com/',fit:['Parker','Porter','Nancy'],summary:'Whimsical carved wooden fish art at the Commons, plus paint-your-own projects.'},
{id:'sanctuary-goods',name:'Sanctuary Goods',town:'Traverse City',type:'art',icon:'🌿',url:'https://sanctuarygoods.com/',fit:['Parker','Nancy'],summary:'Nature-inspired artisan goods, jewelry, fine art and home accents inside the Commons.'},
{id:'m22-tc',name:'M22 Traverse City',town:'Traverse City',type:'gifts',icon:'🌊',url:'https://m22.com/',fit:['Parker','Nancy','Mark'],summary:'Northern Michigan apparel and gifts tied to the road, lakes and conservation.'},
{id:'cherry-republic-tc',name:'Cherry Republic',town:'Traverse City',type:'food',icon:'🍒',url:'https://www.cherryrepublic.com/',fit:['Porter','Parker','Nancy'],summary:'Cherry salsa, candy, preserves, drinks and gifts.'},
{id:'m22-sb',name:'M22 Suttons Bay',town:'Suttons Bay',type:'gifts',icon:'🧢',url:'https://m22.com/',fit:['Mark','Nancy','Parker'],summary:'An easy St. Joseph Street stop for apparel and Up North gifts.'},
{id:'nykamping',name:'Nykamping',town:'Suttons Bay',type:'boutique',icon:'🧵',url:'https://nykamping.com/',fit:['Parker','Nancy'],summary:'Handmade apparel and thoughtfully selected pre-loved textiles.'},
{id:'benjamin-maier',name:'Benjamin Maier Ceramics',town:'Leland',type:'art',icon:'🏺',url:'https://benjaminmaierceramics.com/',fit:['Parker','Nancy'],summary:'Elevated handmade ceramics that feel like a true piece of northern Michigan.'},
{id:'cottage-book',name:'The Cottage Book Shop',town:'Glen Arbor',type:'books',icon:'📖',url:'https://www.cottagebooks.com/',fit:['Parker','Porter','Nancy'],summary:'A cozy independent bookstore perfect for a Sleeping Bear day.'},
{id:'cherry-republic-ga',name:'Cherry Republic Glen Arbor',town:'Glen Arbor',type:'food',icon:'🍒',url:'https://www.cherryrepublic.com/',fit:['Porter','Parker','Nancy'],summary:'The full cherry wonderland with samples, food and gifts.'},
{id:'fishtown',name:'Fishtown Shops',town:'Leland',type:'art',icon:'🎣',url:'https://www.fishtownmi.org/',fit:['Parker','Nancy','Mark'],summary:'Shanty shops, art, food and waterfront atmosphere in one walkable stop.'}
];

const houseGalleryData=[
{id:'exterior',title:'Exterior, yard and waterfront',kicker:'Welcome home',description:'The house sits directly on West Bay with a broad lawn, shoreline, dock, porch and several outdoor gathering spots.',images:['IMG_9768.jpeg','IMG_9769.jpeg','IMG_9770.jpeg','IMG_9775.jpeg','IMG_9779.jpeg','IMG_9788.jpeg','IMG_9789.jpeg','IMG_9792.jpeg','IMG_9793.jpeg','IMG_9795.jpeg','IMG_9796.jpeg','IMG_9797.jpeg','IMG_9798.jpeg','IMG_9799.jpeg','IMG_9800.jpeg','IMG_9814.jpeg','IMG_9817.jpeg']},
{id:'game-room',title:'Garage game room',kicker:'Rainy-day headquarters',description:'Shuffleboard, television, seating and a wide-open view toward the bay make this the second family living room.',images:['IMG_9771.jpeg','IMG_9782.jpeg']},
{id:'kitchen-living',title:'Kitchen, dining and living spaces',kicker:'The gathering zone',description:'The open floor plan includes quartz counters, stainless appliances, a long island, dining space and comfortable living areas.',images:['IMG_9777.jpeg','IMG_9778.jpeg','IMG_9783.jpeg','IMG_9785.jpeg','IMG_9786.jpeg']},
{id:'bathrooms',title:'Bathrooms',kicker:'Two full baths',description:'The listing confirms two full bathrooms, including one tub-or-shower bath and one shower-only bath.',images:['IMG_9784.jpeg','IMG_9791.jpeg']},
{id:'bedrooms',title:'Queen bedrooms',kicker:'Sleep spaces',description:'The property has three queen bedrooms. These are the bedroom photographs currently available from the listing.',images:['IMG_9780.jpeg','IMG_9787.jpeg','IMG_9790.jpeg']},
{id:'patio-hot-tub',title:'Patio, hot tub and outdoor hangouts',kicker:'After the day trip',description:'The seven-person hot tub, backyard, patio and outdoor seating give the house several easy ways to end the day.',images:['IMG_9794.jpeg','IMG_9795.jpeg','IMG_9796.jpeg']},
{id:'maps',title:'Maps and location',kicker:'Where we are',description:'The house is on West Bay along M-22, roughly six miles north of Traverse City and 7.5 miles south of Suttons Bay.',images:['IMG_9806.png','IMG_9807.jpeg','IMG_9815.png']}
];

const allPlaces=[...restaurants.map(x=>({...x,kind:'restaurant'})),...shops.map(x=>({...x,kind:'shop',price:'',tags:[x.type]}))];
let selectedTraveler=localStorage.getItem('tcTraveler')||'Everyone';
if(selectedTraveler==='Jen'){selectedTraveler='Parker';localStorage.setItem('tcTraveler','Parker');}
let favorites=JSON.parse(localStorage.getItem('tcFavoritesV2')||'[]');
let plan=JSON.parse(localStorage.getItem('tcPlanV2')||'{"morning":[],"afternoon":[],"evening":[]}');
let activeRestaurantTags=[];
const dialog=document.getElementById('travelerDialog');
const toast=document.getElementById('toast');

function showTab(name){document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===name));document.querySelectorAll('.bottom-nav [data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.preset){activeRestaurantTags=[b.dataset.preset];renderRestaurantChips();renderRestaurants();}showTab(b.dataset.tab);}));
document.getElementById('enterApp').addEventListener('click',()=>{document.getElementById('landing').hidden=true;document.getElementById('appShell').hidden=false;showTab('home');});
function renderTravelers(){document.getElementById('travelerGrid').innerHTML=travelers.map(t=>`<button class="traveler-option" data-traveler="${t.name}"><span>${t.icon}</span><strong>${t.name}</strong><small>${t.note}</small></button>`).join('');document.getElementById('travelerStrip').innerHTML=travelers.map(t=>`<button class="traveler-chip ${selectedTraveler===t.name?'active':''}" data-traveler="${t.name}">${t.icon} ${t.name}</button>`).join('');document.getElementById('profilePill').textContent=selectedTraveler==='Everyone'?'Choose traveler':`${selectedTraveler}'s view`;document.querySelectorAll('[data-traveler]').forEach(btn=>btn.addEventListener('click',()=>chooseTraveler(btn.dataset.traveler)));}
function chooseTraveler(name){selectedTraveler=name;localStorage.setItem('tcTraveler',name);renderTravelers();renderRestaurants();renderShops();if(dialog.open)dialog.close();showToast(name==='Everyone'?'Showing choices for everyone.':`Showing stronger matches for ${name}.`);}
function renderRestaurantChips(){document.querySelectorAll('#restaurantChips button').forEach(btn=>btn.classList.toggle('active',activeRestaurantTags.includes(btn.dataset.tag)));}
document.querySelectorAll('#restaurantChips button').forEach(btn=>btn.addEventListener('click',()=>{const tag=btn.dataset.tag;activeRestaurantTags=activeRestaurantTags.includes(tag)?activeRestaurantTags.filter(x=>x!==tag):[...activeRestaurantTags,tag];renderRestaurantChips();renderRestaurants();}));
function placeCard(p){const saved=favorites.includes(p.id);const fits=selectedTraveler!=='Everyone'&&p.fit?.includes(selectedTraveler);const tags=(p.tags||[p.type]).slice(0,5).map(t=>`<span class="tag">${t.replaceAll('-',' ')}</span>`).join('');return `<article class="place-card"><div class="icon-badge">${p.icon}</div><h3>${p.name}</h3><div class="place-sub">${p.town}${p.price?` · ${p.price}`:''}${fits?' · Strong match':''}</div><p>${p.summary}</p><div class="tag-row">${tags}</div>${p.menu?`<div class="menu-examples"><strong>Menu examples:</strong> ${p.menu}</div>`:''}<div class="card-actions"><a href="${p.url}" target="_blank" rel="noopener">Official site ↗</a><button class="save-place ${saved?'active':''}" data-save="${p.id}">${saved?'♥ Saved':'♡ Save'}</button></div></article>`;}
function renderRestaurants(){const q=document.getElementById('restaurantSearch').value.toLowerCase().trim(),town=document.getElementById('restaurantTown').value,price=document.getElementById('restaurantPrice').value;let results=restaurants.filter(r=>town==='all'||r.town===town).filter(r=>price==='all'||r.price===price).filter(r=>activeRestaurantTags.every(tag=>r.tags.includes(tag))).filter(r=>`${r.name} ${r.town} ${r.summary} ${r.menu} ${r.tags.join(' ')}`.toLowerCase().includes(q));if(selectedTraveler!=='Everyone')results.sort((a,b)=>Number(b.fit.includes(selectedTraveler))-Number(a.fit.includes(selectedTraveler)));document.getElementById('restaurantResultsNote').textContent=`${results.length} restaurant${results.length===1?'':'s'} match your current filters.`;document.getElementById('restaurantGrid').innerHTML=results.length?results.map(placeCard).join(''):'<p>No exact matches. Remove one filter and try again.</p>';attachSaveButtons();}
function renderShops(){const q=document.getElementById('shopSearch').value.toLowerCase().trim(),town=document.getElementById('shopTown').value,type=document.getElementById('shopType').value;let results=shops.filter(s=>town==='all'||s.town===town).filter(s=>type==='all'||s.type===type).filter(s=>`${s.name} ${s.town} ${s.type} ${s.summary}`.toLowerCase().includes(q));if(selectedTraveler!=='Everyone')results.sort((a,b)=>Number(Boolean(b.fit?.includes(selectedTraveler)))-Number(Boolean(a.fit?.includes(selectedTraveler))));document.getElementById('shopGrid').innerHTML=results.length?results.map(placeCard).join(''):'<p>No matches yet. Try another town or category.</p>';attachSaveButtons();}
function attachSaveButtons(){document.querySelectorAll('[data-save]').forEach(btn=>btn.addEventListener('click',()=>toggleFavorite(btn.dataset.save)));}
function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem('tcFavoritesV2',JSON.stringify(favorites));renderRestaurants();renderShops();renderPlanner();updateStats();showToast(favorites.includes(id)?'Saved to the family shortlist.':'Removed from saved places.');}
function plannerCard(p){return `<div class="planner-card" draggable="true" data-id="${p.id}"><strong>${p.icon} ${p.name}</strong><small>${p.town}${p.price?` · ${p.price}`:''}</small></div>`;}
function renderPlanner(){const planned=Object.values(plan).flat(),available=allPlaces.filter(p=>favorites.includes(p.id)&&!planned.includes(p.id));document.getElementById('plannerIdeas').innerHTML=available.length?available.map(plannerCard).join(''):'<small>Save restaurants or shops to fill this tray.</small>';['morning','afternoon','evening'].forEach(slot=>{document.getElementById(slot).innerHTML=plan[slot].map(id=>allPlaces.find(p=>p.id===id)).filter(Boolean).map(plannerCard).join('');});attachDrag();updateStats();}
function attachDrag(){document.querySelectorAll('.planner-card').forEach(card=>card.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',card.dataset.id)));document.querySelectorAll('.drop-zone').forEach(zone=>{zone.addEventListener('dragover',e=>{e.preventDefault();zone.classList.add('drag-over')});zone.addEventListener('dragleave',()=>zone.classList.remove('drag-over'));zone.addEventListener('drop',e=>{e.preventDefault();zone.classList.remove('drag-over');const id=e.dataTransfer.getData('text/plain');Object.keys(plan).forEach(k=>plan[k]=plan[k].filter(x=>x!==id));plan[zone.id].push(id);savePlan();});});}
function savePlan(){localStorage.setItem('tcPlanV2',JSON.stringify(plan));renderPlanner();showToast('Day plan updated.');}
function updateStats(){document.getElementById('favoriteCount').textContent=favorites.length;document.getElementById('plannedCount').textContent=Object.values(plan).flat().length;}
function updateCountdown(){const diff=Math.max(0,new Date('2026-08-23T16:00:00')-new Date());document.getElementById('days').textContent=Math.floor(diff/86400000);document.getElementById('hours').textContent=Math.floor(diff%86400000/3600000);document.getElementById('minutes').textContent=Math.floor(diff%3600000/60000);}
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2300);}
function renderHouseGalleries(){const root=document.getElementById('houseGalleries');root.innerHTML=houseGalleryData.map(g=>`<section class="gallery-section" data-gallery="${g.id}" data-index="0"><div class="gallery-head"><div><p class="eyebrow dark">${g.kicker}</p><h3>${g.title}</h3><p>${g.description}</p></div><span class="gallery-count">1 / ${g.images.length}</span></div><div class="gallery-stage"><img src="Assets/Assets/Images/${g.images[0]}" alt="${g.title} photo 1" data-open-photo><button class="gallery-control prev" aria-label="Previous photo">‹</button><button class="gallery-control next" aria-label="Next photo">›</button><div class="gallery-caption"><strong>${g.title}</strong><small>Swipe or use arrows</small></div></div><div class="gallery-thumbs">${g.images.map((img,i)=>`<button class="gallery-thumb ${i===0?'active':''}" data-thumb="${i}"><img src="Assets/Assets/Images/${img}" alt=""></button>`).join('')}</div></section>`).join('');root.querySelectorAll('.gallery-section').forEach(section=>{const gallery=houseGalleryData.find(g=>g.id===section.dataset.gallery),stage=section.querySelector('.gallery-stage');const update=n=>{const i=(n+gallery.images.length)%gallery.images.length;section.dataset.index=i;const img=stage.querySelector('img');img.src=`Assets/Assets/Images/${gallery.images[i]}`;img.alt=`${gallery.title} photo ${i+1}`;section.querySelector('.gallery-count').textContent=`${i+1} / ${gallery.images.length}`;section.querySelectorAll('.gallery-thumb').forEach((t,j)=>t.classList.toggle('active',j===i));section.querySelector('.gallery-thumbs').children[i]?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});};section.querySelector('.prev').onclick=()=>update(Number(section.dataset.index)-1);section.querySelector('.next').onclick=()=>update(Number(section.dataset.index)+1);section.querySelectorAll('[data-thumb]').forEach(btn=>btn.onclick=()=>update(Number(btn.dataset.thumb)));let startX=0;stage.addEventListener('touchstart',e=>startX=e.changedTouches[0].clientX,{passive:true});stage.addEventListener('touchend',e=>{const d=e.changedTouches[0].clientX-startX;if(Math.abs(d)>45)update(Number(section.dataset.index)+(d<0?1:-1));},{passive:true});stage.querySelector('[data-open-photo]').onclick=()=>openPhoto(gallery,Number(section.dataset.index));});}
function openPhoto(gallery,index){const d=document.getElementById('photoDialog');document.getElementById('dialogPhoto').src=`Assets/Assets/Images/${gallery.images[index]}`;document.getElementById('dialogCaption').textContent=`${gallery.title} · photo ${index+1} of ${gallery.images.length}`;d.showModal();}
document.getElementById('profilePill').onclick=()=>dialog.showModal();document.querySelector('#travelerDialog .dialog-close').onclick=()=>dialog.close();document.querySelector('.photo-close').onclick=()=>document.getElementById('photoDialog').close();document.getElementById('clearPlan').onclick=()=>{plan={morning:[],afternoon:[],evening:[]};savePlan();};['restaurantSearch','restaurantTown','restaurantPrice'].forEach(id=>document.getElementById(id).addEventListener('input',renderRestaurants));['shopSearch','shopTown','shopType'].forEach(id=>document.getElementById(id).addEventListener('input',renderShops));
renderTravelers();renderRestaurantChips();renderRestaurants();renderShops();renderPlanner();renderHouseGalleries();updateStats();updateCountdown();setInterval(updateCountdown,60000);