(() => {
  const FAMILY=['Parker','Blake','Porter','Mark','Nancy'];
  const ICONS={Parker:'🧚',Blake:'🧭',Porter:'🎮',Mark:'🚤',Nancy:'🍒'};
  const SLOTS=['morning','afternoon','evening'];
  const SLOT_NAMES={morning:'Morning',afternoon:'Afternoon',evening:'Evening'};
  const SLOT_ICONS={morning:'☀️',afternoon:'🌤️',evening:'🌙'};
  const META_KEY='tcPlannerMetaV1',SHARED_KEY='planner_meta_v1';
  const ZONES=[
    {id:'wander-grand-traverse-commons',name:'Grand Traverse Commons Wander',area:'Grand Traverse Commons',icon:'🧺',minutes:150,cluster:'commons',description:'Give the Commons a real 2½-hour block, then casually roam shops, galleries, gardens, food stops, and historic grounds.',match:p=>/grand traverse commons/i.test(`${p.area||''}`)},
    {id:'wander-fishtown-leland',name:'Fishtown + Leland Wander',area:'Leland / Fishtown',icon:'🎣',minutes:150,cluster:'leland',description:'One loose block for the shanties, harbor, shops, food, and whatever looks interesting once you are standing there.',match:p=>/leland|fishtown/i.test(`${p.area||''} ${p.town||''}`)},
    {id:'wander-downtown-tc',name:'Downtown Traverse City Wander',area:'Traverse City / Downtown',icon:'🏙️',minutes:120,cluster:'downtown',description:'Park once and wander books, records, gifts, food, waterfront, and downtown side streets without turning every shop into an appointment.',match:p=>/downtown/i.test(`${p.area||''}`)},
    {id:'wander-suttons-bay',name:'Suttons Bay Wander',area:'Suttons Bay',icon:'⛵',minutes:120,cluster:'suttons',description:'A compact village block for shops, lunch, marina views, and low-pressure wandering.',match:p=>/suttons bay/i.test(`${p.area||''} ${p.town||''}`)},
    {id:'wander-glen-arbor',name:'Glen Arbor Wander',area:'Glen Arbor',icon:'🌲',minutes:150,cluster:'glen_arbor',description:'A flexible Glen Arbor block for books, cherries, lunch, beach energy, and whatever earns a spontaneous yes.',match:p=>/glen arbor/i.test(`${p.area||''} ${p.town||''}`)&&!/sleeping bear/i.test(`${p.area||''}`)}
  ];
  const POINTS={house:[44.86,-85.68],downtown:[44.763,-85.621],commons:[44.742,-85.641],west_tc:[44.765,-85.66],south_tc:[44.715,-85.62],east_tc:[44.755,-85.56],boardman:[44.715,-85.58],old_mission:[44.94,-85.49],suttons:[44.976,-85.651],leland:[45.023,-85.760],glen_arbor:[44.897,-85.986],sleeping_bear:[44.87,-86.05],williamsburg:[44.78,-85.40],east_jordan:[45.158,-85.129],traverse:[44.76,-85.62]};
  let meta=loadMeta(),shelfMode=localStorage.getItem('tcPlannerShelfMode')||'family',initialized=false;

  const safe=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
  const copy=v=>JSON.parse(JSON.stringify(v));
  function defaultMeta(){return{version:1,entries:{},availabilityBlocks:[{id:'parker-webinar-wed26-morning',day:'wed26',slot:'morning',person:'Parker',title:'Webinar / laptop availability',locked:true}]};}
  function normalizeMeta(v){const d=defaultMeta();if(!v||typeof v!=='object'||Array.isArray(v))return d;return{version:1,entries:v.entries&&typeof v.entries==='object'&&!Array.isArray(v.entries)?v.entries:{},availabilityBlocks:Array.isArray(v.availabilityBlocks)?v.availabilityBlocks:d.availabilityBlocks};}
  function loadMeta(){try{return normalizeMeta(JSON.parse(localStorage.getItem(META_KEY)||'null'));}catch{return defaultMeta();}}
  function saveMeta(){localStorage.setItem(META_KEY,JSON.stringify(meta));window.TCShared?.write?.(SHARED_KEY,meta).catch(e=>console.warn('Planner details saved locally only:',e?.message));}
  function toast(m){if(typeof showToast==='function')showToast(m);}

  function addZones(){ZONES.forEach(z=>{if(allPlaces.some(p=>p.id===z.id))return;allPlaces.push({id:z.id,name:z.name,town:z.area,area:z.area,type:'wander',kind:'activity',plannerType:'wander',virtual:true,icon:z.icon,url:'#',tags:['wander-zone','low-energy'],fit:['Everyone'],dog:'Individual stops vary',summary:z.description,durationMinutes:z.minutes,cluster:z.cluster});});}
  const zoneFor=id=>ZONES.find(z=>z.id===id);
  const isZone=p=>!!(p&&(p.plannerType==='wander'||zoneFor(p.id)));
  const zoneMembers=z=>z?allPlaces.filter(p=>!p.virtual&&z.match(p)):[];
  function ratingInfo(p){if(!p||isZone(p))return{stats:{entries:[],count:0,average:0},top:0,high:0,everybody:false,majority:false,big:null};const stats=window.TCHeartRatings?.stats?.(p.id)||{entries:[],count:0,average:0};const vals=stats.entries.map(x=>x.rating),top=vals.length?Math.max(...vals):0,high=vals.filter(x=>x>=4).length;return{stats,top,high,everybody:stats.count===FAMILY.length&&vals.every(x=>x>=4),majority:high>=3,big:stats.entries.find(x=>x.rating===5)||null};}
  function ratingLabel(p){if(isZone(p)){const s=zoneSummary(zoneFor(p.id));return`${s.priority} priorities · ${s.nearby} while-we're-here`; }const i=ratingInfo(p);if(!i.stats.count)return'Not rated yet';if(i.everybody)return`❤️ Everybody loves it · ${i.stats.average.toFixed(1)}`;if(i.big)return`⭐ ${i.big.name}'s big pick · ${i.stats.average.toFixed(1)}`;if(i.majority)return`💛 Strong majority · ${i.stats.average.toFixed(1)}`;return`${i.stats.average.toFixed(1)} hearts · ${i.stats.count} rated`;}
  function zoneSummary(z){let priority=0,nearby=0;const members=zoneMembers(z);members.forEach(p=>{const i=ratingInfo(p);if(i.everybody||i.majority||i.big||i.stats.average>=3.5)priority++;else if(i.top>=2||i.stats.average>=2)nearby++;});return{total:members.length,priority,nearby};}

  const entryKey=(day,id)=>`${day}:${id}`;
  function entryMeta(day,p){const raw=meta.entries[entryKey(day,p.id)]||{};const attendees=Array.isArray(raw.attendees)&&raw.attendees.length?raw.attendees.filter(n=>FAMILY.includes(n)):FAMILY.slice();return{locked:!!raw.locked,attendees,durationMinutes:Number(raw.durationMinutes)||Number(p.durationMinutes)||zoneFor(p.id)?.minutes||90};}
  function setEntry(day,id,patch){const p=allPlaces.find(x=>x.id===id);if(!p)return;const k=entryKey(day,id);meta.entries[k]={...entryMeta(day,p),...(meta.entries[k]||{}),...patch};saveMeta();}
  function moveEntry(from,to,id){if(!from||from===to)return;const a=entryKey(from,id),b=entryKey(to,id);if(meta.entries[a]){meta.entries[b]=meta.entries[a];delete meta.entries[a];saveMeta();}}
  function deleteEntry(day,id){delete meta.entries[entryKey(day,id)];saveMeta();}

  function cluster(p){if(!p)return'traverse';if(p.cluster)return p.cluster;const t=`${p.area||''} ${p.town||''}`.toLowerCase();if(t.includes('at the house'))return'house';if(t.includes('grand traverse commons'))return'commons';if(t.includes('boardman river'))return'boardman';if(t.includes('old mission'))return'old_mission';if(t.includes('suttons bay'))return'suttons';if(t.includes('fishtown')||t.includes('leland'))return'leland';if(t.includes('sleeping bear')||t.includes('empire'))return'sleeping_bear';if(t.includes('glen arbor'))return'glen_arbor';if(t.includes('williamsburg')||t.includes('east of traverse'))return'williamsburg';if(t.includes('east jordan'))return'east_jordan';if(t.includes('south side'))return'south_tc';if(t.includes('east side'))return'east_tc';if(t.includes('west side')||t.includes('west bay'))return'west_tc';if(t.includes('downtown'))return'downtown';return'traverse';}
  function miles(a,b){const r=x=>x*Math.PI/180,R=3958.8,dlat=r(b[0]-a[0]),dlon=r(b[1]-a[1]),x=Math.sin(dlat/2)**2+Math.sin(dlon/2)**2*Math.cos(r(a[0]))*Math.cos(r(b[0]));return 2*R*Math.asin(Math.sqrt(x));}
  function drive(a,b){if(!a||!b)return null;if(a===b)return 4;const mins=(miles(POINTS[a]||POINTS.traverse,POINTS[b]||POINTS.traverse)*1.28/42*60)+4;return Math.max(5,Math.round(mins/5)*5);}
  function sequence(day){return SLOTS.flatMap(slot=>(plan?.[day]?.[slot]||[]).map(id=>({id,slot,place:allPlaces.find(p=>p.id===id)})).filter(x=>x.place));}
  const clustersFor=day=>[...new Set(sequence(day).map(x=>cluster(x.place)))];
  function route(day){const s=sequence(day);if(!s.length)return{minutes:0,label:'Open canvas',tone:'empty',detail:'Start with an anchor or wander zone.'};let total=0;for(let i=1;i<s.length;i++)total+=drive(cluster(s[i-1].place),cluster(s[i].place))||0;const c=clustersFor(day);if(total<=30&&c.length<=2)return{minutes:total,label:'Nicely clustered',tone:'good',detail:`${c.length} area${c.length===1?'':'s'} · ≈${total} min between stops`};if(total<=65)return{minutes:total,label:'Some bouncing around',tone:'warn',detail:`${c.length} areas · ≈${total} min between stops`};return{minutes:total,label:'Windshield-heavy',tone:'bad',detail:`${c.length} areas · ≈${total} min between stops`};}
  function nearby(p,day){const cs=clustersFor(day);if(!cs.length)return null;const vals=cs.map(c=>drive(c,cluster(p))).filter(Number.isFinite);return vals.length?Math.min(...vals):null;}

  function scheduledLocation(id){for(const d of tripDays)for(const slot of SLOTS)if((plan?.[d.id]?.[slot]||[]).includes(id))return{day:d.id,slot};return null;}
  const scheduled=id=>!!scheduledLocation(id);
  function candidates(){return allPlaces.filter(p=>!p.virtual&&!scheduled(p.id)).filter(p=>{const i=ratingInfo(p);return i.stats.count>0||(typeof favorites!=='undefined'&&favorites.includes(p.id));});}
  function shelfItems(){if(shelfMode==='wander')return ZONES.map(z=>allPlaces.find(p=>p.id===z.id)).filter(Boolean).filter(p=>!scheduled(p.id));let a=candidates();if(shelfMode==='big')a=a.filter(p=>ratingInfo(p).big);else if(shelfMode==='nearby')a=a.filter(p=>{const i=ratingInfo(p),m=nearby(p,activeDay);return i.top>=2&&m!==null&&m<=15;});else if(shelfMode==='all')a=a.filter(p=>{const i=ratingInfo(p);return i.top>=2||i.stats.average>=2;});else a=a.filter(p=>{const i=ratingInfo(p);return i.everybody||i.majority||i.big||i.stats.average>=3;});return a.sort((x,y)=>{const a=ratingInfo(x),b=ratingInfo(y),as=a.stats.average+(a.big?2:0)+(a.majority?1:0),bs=b.stats.average+(b.big?2:0)+(b.majority?1:0);return bs-as||x.name.localeCompare(y.name);});}
  function duration(n){if(n%60===0)return`${n/60} hr`;if(n>60)return`${Math.floor(n/60)} hr ${n%60} min`;return`${n} min`;}
  function people(att){return att.length===FAMILY.length?'<span class="plan-all-people">Everyone</span>':att.map(n=>`<span class="plan-person-dot" title="${safe(n)}">${safe(n[0])}</span>`).join('');}
  function conflicts(day,slot,att){return meta.availabilityBlocks.filter(b=>b.day===day&&b.slot===slot&&att.includes(b.person));}

  function shelfCard(p){const i=ratingInfo(p),m=nearby(p,activeDay),near=i.top>=2&&m!==null&&m<=15?`<span class="plan-nearby">📍 Nearby ${safe(tripDays.find(d=>d.id===activeDay)?.label||'day')} plans · ≈${m} min</span>`:'',big=i.big?`<span class="plan-big-pick">⭐ ${safe(i.big.name)} REALLY wants this</span>`:'';return`<article class="plan-shelf-card" draggable="true" data-plan-id="${safe(p.id)}"><div class="plan-shelf-card-top"><span class="plan-place-icon">${p.icon||'📍'}</span><div><strong>${safe(p.name)}</strong><small>${safe(p.area||p.town)}</small></div></div><div class="plan-rating-line">${safe(ratingLabel(p))}</div>${near}${big}<div class="plan-shelf-actions"><button type="button" data-plan-add="${safe(p.id)}">Add to plan</button></div></article>`;}
  function wanderCard(p){const z=zoneFor(p.id),s=zoneSummary(z),members=zoneMembers(z).map(x=>({p:x,i:ratingInfo(x)})).filter(x=>x.i.top>=2||x.i.stats.average>=2).sort((a,b)=>(b.i.stats.average+(b.i.big?2:0))-(a.i.stats.average+(a.i.big?2:0))).slice(0,7);return`<article class="plan-shelf-card plan-wander-card" draggable="true" data-plan-id="${safe(p.id)}"><div class="plan-shelf-card-top"><span class="plan-place-icon">${p.icon}</span><div><strong>${safe(p.name)}</strong><small>${duration(z.minutes)} · ${s.total} places in area</small></div></div><p>${safe(z.description)}</p><div class="wander-metrics"><span>❤️ ${s.priority} priorities</span><span>📍 ${s.nearby} while-we're-here</span></div>${members.length?`<details><summary>See likely stops</summary><div class="wander-mini-list">${members.map(x=>`<span>${safe(x.p.name)} <small>${x.i.stats.count?x.i.stats.average.toFixed(1):''}♥</small></span>`).join('')}</div></details>`:''}<div class="plan-shelf-actions"><button type="button" data-plan-add="${safe(p.id)}">Add wander block</button></div></article>`;}
  function driveBadge(seq,index){if(index<=0)return'';const m=drive(cluster(seq[index-1]?.place),cluster(seq[index]?.place));if(m<=5)return'<span class="plan-drive-badge good">📍 Same area</span>';if(m<=15)return`<span class="plan-drive-badge good">📍 ≈${m} min from previous</span>`;if(m>=35)return`<span class="plan-drive-badge bad">⚠️ ≈${m} min from previous</span>`;return`<span class="plan-drive-badge">🚙 ≈${m} min from previous</span>`;}
  function stopCard(day,slot,p,seq,index){const d=entryMeta(day,p),c=conflicts(day,slot,d.attendees),zs=isZone(p)?zoneSummary(zoneFor(p.id)):null;return`<article class="plan-stop-card ${isZone(p)?'is-wander':''} ${d.locked?'is-locked':''}" draggable="${d.locked?'false':'true'}" data-plan-stop="${safe(p.id)}" data-plan-day="${day}">${driveBadge(seq,index)}<div class="plan-stop-head"><span>${p.icon||'📍'}</span><div><strong>${safe(p.name)}</strong><small>${safe(p.area||'')}</small></div><button class="plan-lock" data-plan-lock="${safe(p.id)}" data-day="${day}" aria-label="${d.locked?'Unlock':'Lock'}">${d.locked?'🔒':'🔓'}</button></div><div class="plan-stop-meta"><span>🕒 ${duration(d.durationMinutes)}</span><button class="plan-people" data-plan-details="${safe(p.id)}" data-day="${day}">👥 ${people(d.attendees)}</button></div>${zs?`<div class="wander-metrics"><span>❤️ ${zs.priority} priorities</span><span>📍 ${zs.nearby} optional</span></div>`:`<div class="plan-rating-line">${safe(ratingLabel(p))}</div>`}${c.length?`<div class="plan-conflict">⚠️ ${c.map(x=>`${safe(x.person)} unavailable: ${safe(x.title)}`).join(' · ')}</div>`:''}<div class="plan-stop-actions"><button data-plan-remove="${safe(p.id)}" data-day="${day}" ${d.locked?'disabled':''}>Remove</button></div></article>`;}
  function availabilityCard(b){return`<article class="availability-card"><span>${ICONS[b.person]||'👤'}</span><div><strong>${safe(b.person)} unavailable</strong><small>${safe(b.title)}</small></div><button data-remove-block="${safe(b.id)}" aria-label="Remove availability">×</button></article>`;}
  function dayColumn(day){const r=route(day.id),seq=sequence(day.id);let index=0;const slots=SLOTS.map(slot=>{const cards=(plan?.[day.id]?.[slot]||[]).map(id=>allPlaces.find(p=>p.id===id)).filter(Boolean).map(p=>stopCard(day.id,slot,p,seq,index++)).join(''),blocks=meta.availabilityBlocks.filter(b=>b.day===day.id&&b.slot===slot).map(availabilityCard).join('');return`<section class="plan-slot" data-plan-drop-day="${day.id}" data-plan-drop-slot="${slot}"><header><span>${SLOT_ICONS[slot]}</span><strong>${SLOT_NAMES[slot]}</strong></header><div class="plan-slot-body">${blocks}${cards||'<span class="plan-empty-slot">Drop something here</span>'}</div></section>`;}).join('');return`<article class="plan-day-column ${activeDay===day.id?'is-active':''}"><header class="plan-day-head"><button data-plan-focus-day="${day.id}"><strong>${safe(day.label)}</strong><small>${safe(day.title)}</small></button><div class="plan-route-score ${r.tone}"><strong>${safe(r.label)}</strong><small>${safe(r.detail)}</small></div></header>${slots}</article>`;}

  function shell(){return`<section class="plan-trip-hero"><div><p class="eyebrow dark">Plan the trip</p><h2>Build the days without turning vacation into logistics homework.</h2><p>Drag anchors and wander blocks onto the calendar. Hearts set priority, geography decides what is easy once you are already there.</p></div><div class="plan-hero-actions"><button id="addAvailabilityBlock">+ Personal availability</button><button id="openDecidePreview">🦦 Let's Decide</button></div></section><section class="plan-intel-strip" id="planIntelStrip"></section><div class="plan-workspace"><aside class="plan-shelf"><div class="plan-shelf-heading"><div><p class="eyebrow dark">Trip shelf</p><h3>Still flexible</h3></div><small>Drag on Mac. Tap Add on mobile.</small></div><div class="plan-shelf-tabs" id="planShelfTabs"><button data-shelf="family">❤️ Family favorites</button><button data-shelf="big">⭐ Big picks</button><button data-shelf="nearby">📍 Nearby</button><button data-shelf="wander">🧺 Wander zones</button><button data-shelf="all">♡ 2+ heart options</button></div><div class="plan-shelf-list" id="planShelfList"></div></aside><section class="plan-calendar-wrap"><div class="plan-calendar-toolbar"><div><strong>Five-day board</strong><small>Drive times are rough planning estimates, not live traffic.</small></div><button id="clearActiveDay">Clear selected day</button></div><div class="plan-calendar" id="planCalendar"></div></section></div><dialog id="plannerAddDialog" class="planner-dialog"></dialog><dialog id="plannerDetailsDialog" class="planner-dialog"></dialog><dialog id="plannerAvailabilityDialog" class="planner-dialog"></dialog><dialog id="plannerDecisionDialog" class="planner-dialog planner-decision-dialog"></dialog>`;}
  function renderIntel(){const root=document.getElementById('planIntelStrip');if(!root)return;const seq=tripDays.flatMap(d=>sequence(d.id)),driveTotal=tripDays.reduce((s,d)=>s+route(d.id).minutes,0),locked=tripDays.reduce((s,d)=>s+sequence(d.id).filter(x=>entryMeta(d.id,x.place).locked).length,0),wanders=seq.filter(x=>isZone(x.place)).length;root.innerHTML=`<div><strong>${seq.length}</strong><span>scheduled blocks</span></div><div><strong>${wanders}</strong><span>wander zones</span></div><div><strong>${locked}</strong><span>locked anchors</span></div><div><strong>≈${driveTotal}</strong><span>drive min</span></div>`;}
  function renderShelf(){const tabs=document.getElementById('planShelfTabs'),list=document.getElementById('planShelfList');if(!tabs||!list)return;tabs.querySelectorAll('[data-shelf]').forEach(b=>b.classList.toggle('active',b.dataset.shelf===shelfMode));const near=tabs.querySelector('[data-shelf="nearby"]');if(near)near.textContent=`📍 Nearby ${tripDays.find(d=>d.id===activeDay)?.label||'day'}`;const items=shelfItems();list.innerHTML=items.length?items.map(p=>isZone(p)?wanderCard(p):shelfCard(p)).join(''):'<div class="plan-shelf-empty">Nothing in this bucket yet. Try another shelf view.</div>';bindShelf();}
  function renderCalendar(){const root=document.getElementById('planCalendar');if(!root)return;root.innerHTML=tripDays.map(dayColumn).join('');bindCalendar();}
  function renderNewPlanner(){if(!document.getElementById('planCalendar'))return;renderIntel();renderShelf();renderCalendar();if(typeof updateStats==='function')updateStats();}

  function addTo(day,slot,id,fromDay=''){const p=allPlaces.find(x=>x.id===id);if(!p||!plan?.[day]?.[slot])return;const current=scheduledLocation(id);if(current&&entryMeta(current.day,p).locked&&(current.day!==day||current.slot!==slot)){toast('That stop is locked. Unlock it before moving it.');return;}Object.values(plan).forEach(d=>Object.keys(d).forEach(k=>d[k]=d[k].filter(x=>x!==id)));plan[day][slot].push(id);moveEntry(fromDay||current?.day,day,id);activeDay=day;localStorage.setItem('tcActiveDay',activeDay);savePlan();}
  function removeFrom(day,id){const p=allPlaces.find(x=>x.id===id);if(!p)return;if(entryMeta(day,p).locked){toast('That stop is locked. Unlock it before removing it.');return;}SLOTS.forEach(s=>plan[day][s]=(plan[day][s]||[]).filter(x=>x!==id));deleteEntry(day,id);savePlan();}
  function toggleLock(day,id){const p=allPlaces.find(x=>x.id===id);if(!p)return;const d=entryMeta(day,p);setEntry(day,id,{locked:!d.locked});toast(d.locked?'Stop unlocked.':'Stop locked in place.');renderNewPlanner();}

  function bindShelf(){document.querySelectorAll('.plan-shelf-card[draggable="true"]').forEach(c=>c.addEventListener('dragstart',e=>{e.dataTransfer.setData('application/x-tc-plan',JSON.stringify({id:c.dataset.planId,fromDay:''}));e.dataTransfer.effectAllowed='move';}));document.querySelectorAll('[data-plan-add]').forEach(b=>b.addEventListener('click',()=>openAdd(b.dataset.planAdd)));}
  function bindCalendar(){document.querySelectorAll('[data-plan-focus-day]').forEach(b=>b.addEventListener('click',()=>{activeDay=b.dataset.planFocusDay;localStorage.setItem('tcActiveDay',activeDay);renderNewPlanner();}));document.querySelectorAll('.plan-stop-card[draggable="true"]').forEach(c=>c.addEventListener('dragstart',e=>{e.dataTransfer.setData('application/x-tc-plan',JSON.stringify({id:c.dataset.planStop,fromDay:c.dataset.planDay}));e.dataTransfer.effectAllowed='move';}));document.querySelectorAll('[data-plan-drop-day]').forEach(z=>{z.addEventListener('dragover',e=>{e.preventDefault();z.classList.add('drag-over');});z.addEventListener('dragleave',()=>z.classList.remove('drag-over'));z.addEventListener('drop',e=>{e.preventDefault();z.classList.remove('drag-over');try{const d=JSON.parse(e.dataTransfer.getData('application/x-tc-plan')||'{}');if(d.id)addTo(z.dataset.planDropDay,z.dataset.planDropSlot,d.id,d.fromDay);}catch{}});});document.querySelectorAll('[data-plan-lock]').forEach(b=>b.addEventListener('click',()=>toggleLock(b.dataset.day,b.dataset.planLock)));document.querySelectorAll('[data-plan-remove]').forEach(b=>b.addEventListener('click',()=>removeFrom(b.dataset.day,b.dataset.planRemove)));document.querySelectorAll('[data-plan-details]').forEach(b=>b.addEventListener('click',()=>openDetails(b.dataset.day,b.dataset.planDetails)));document.querySelectorAll('[data-remove-block]').forEach(b=>b.addEventListener('click',()=>{meta.availabilityBlocks=meta.availabilityBlocks.filter(x=>x.id!==b.dataset.removeBlock);saveMeta();renderNewPlanner();}));}

  function openAdd(id){const p=allPlaces.find(x=>x.id===id),dlg=document.getElementById('plannerAddDialog');if(!p||!dlg)return;let day=activeDay;dlg.innerHTML=`<button class="planner-dialog-close" data-close>×</button><p class="eyebrow dark">Add to plan</p><h3>${safe(p.name)}</h3><p>Choose a day and part of the day.</p><div class="planner-add-days">${tripDays.map(d=>`<button data-add-day="${d.id}" class="${d.id===day?'selected':''}">${safe(d.label)}</button>`).join('')}</div><div class="planner-add-slots">${SLOTS.map(s=>`<button data-add-slot="${s}">${SLOT_ICONS[s]} ${SLOT_NAMES[s]}</button>`).join('')}</div>`;dlg.querySelectorAll('[data-add-day]').forEach(b=>b.onclick=()=>{day=b.dataset.addDay;dlg.querySelectorAll('[data-add-day]').forEach(x=>x.classList.toggle('selected',x===b));});dlg.querySelectorAll('[data-add-slot]').forEach(b=>b.onclick=()=>{addTo(day,b.dataset.addSlot,id);dlg.close();});dlg.querySelector('[data-close]').onclick=()=>dlg.close();dlg.showModal();}
  function openDetails(day,id){const p=allPlaces.find(x=>x.id===id),dlg=document.getElementById('plannerDetailsDialog');if(!p||!dlg)return;const d=entryMeta(day,p);dlg.innerHTML=`<button class="planner-dialog-close" data-close>×</button><p class="eyebrow dark">Plan details</p><h3>${safe(p.name)}</h3><label class="planner-field">How long?<select id="planDuration">${[30,45,60,90,120,150,180,240].map(n=>`<option value="${n}" ${n===d.durationMinutes?'selected':''}>${duration(n)}</option>`).join('')}</select></label><p class="planner-field-label">Who's going?</p><div class="planner-people-grid">${FAMILY.map(n=>`<label><input type="checkbox" value="${n}" ${d.attendees.includes(n)?'checked':''}><span>${ICONS[n]} ${n}</span></label>`).join('')}</div><button class="planner-primary-action" data-save-details>Save details</button>`;dlg.querySelector('[data-save-details]').onclick=()=>{const attendees=[...dlg.querySelectorAll('input:checked')].map(x=>x.value);if(!attendees.length){toast('Choose at least one person.');return;}setEntry(day,id,{attendees,durationMinutes:Number(dlg.querySelector('#planDuration').value)});dlg.close();renderNewPlanner();};dlg.querySelector('[data-close]').onclick=()=>dlg.close();dlg.showModal();}
  function openAvailability(){const dlg=document.getElementById('plannerAvailabilityDialog');if(!dlg)return;dlg.innerHTML=`<button class="planner-dialog-close" data-close>×</button><p class="eyebrow dark">Personal availability</p><h3>Block time for one person</h3><label class="planner-field">Person<select id="avPerson">${FAMILY.map(n=>`<option>${n}</option>`).join('')}</select></label><label class="planner-field">What do they need to be available for?<input id="avTitle" value="Personal commitment"></label><label class="planner-field">Day<select id="avDay">${tripDays.map(d=>`<option value="${d.id}" ${d.id===activeDay?'selected':''}>${d.label}</option>`).join('')}</select></label><label class="planner-field">Part of day<select id="avSlot">${SLOTS.map(s=>`<option value="${s}">${SLOT_NAMES[s]}</option>`).join('')}</select></label><button class="planner-primary-action" data-save-av>Save availability block</button>`;dlg.querySelector('[data-save-av]').onclick=()=>{meta.availabilityBlocks.push({id:`availability-${Date.now()}`,person:dlg.querySelector('#avPerson').value,title:dlg.querySelector('#avTitle').value.trim()||'Personal commitment',day:dlg.querySelector('#avDay').value,slot:dlg.querySelector('#avSlot').value,locked:true});saveMeta();dlg.close();renderNewPlanner();};dlg.querySelector('[data-close]').onclick=()=>dlg.close();dlg.showModal();}
  function openDecide(){const dlg=document.getElementById('plannerDecisionDialog');if(!dlg)return;const top=candidates().sort((a,b)=>{const x=ratingInfo(a),y=ratingInfo(b);return(y.stats.average+(y.big?2:0)+(y.majority?1:0))-(x.stats.average+(x.big?2:0)+(x.majority?1:0));}).slice(0,10);dlg.innerHTML=`<button class="planner-dialog-close" data-close>×</button><p class="eyebrow dark">Let's Decide</p><h3>What still deserves a family conversation?</h3><p>This first decision view surfaces the strongest unrouted choices without erasing anybody's big pick.</p><div class="decision-preview-list">${top.map(p=>`<button data-decide="${safe(p.id)}"><strong>${p.icon||'📍'} ${safe(p.name)}</strong><small>${safe(ratingLabel(p))} · ${safe(p.area||'')}</small></button>`).join('')}</div>`;dlg.querySelectorAll('[data-decide]').forEach(b=>b.onclick=()=>{dlg.close();openAdd(b.dataset.decide);});dlg.querySelector('[data-close]').onclick=()=>dlg.close();dlg.showModal();}
  function clearDay(){const locked=sequence(activeDay).filter(x=>entryMeta(activeDay,x.place).locked);if(locked.length){toast('This day has locked stops. Unlock them before clearing the day.');return;}const ids=sequence(activeDay).map(x=>x.id);plan[activeDay]=emptyDay();ids.forEach(id=>delete meta.entries[entryKey(activeDay,id)]);saveMeta();savePlan();}
  function bindShell(){document.querySelectorAll('[data-shelf]').forEach(b=>b.onclick=()=>{shelfMode=b.dataset.shelf;localStorage.setItem('tcPlannerShelfMode',shelfMode);renderShelf();});document.getElementById('addAvailabilityBlock').onclick=openAvailability;document.getElementById('openDecidePreview').onclick=openDecide;document.getElementById('clearActiveDay').onclick=clearDay;}

  async function hydrateMeta(){try{const shared=await window.TCShared?.read?.(SHARED_KEY);if(shared&&typeof shared==='object'&&Object.keys(shared).length){meta=normalizeMeta(shared);localStorage.setItem(META_KEY,JSON.stringify(meta));renderNewPlanner();}else saveMeta();}catch(e){console.warn('Planner details are using this device only:',e?.message);}}
  function init(){if(initialized)return true;const panel=document.querySelector('[data-panel="planner"]');if(!panel||typeof allPlaces==='undefined'||typeof plan==='undefined'||!window.TCHeartRatings)return false;initialized=true;addZones();panel.classList.add('plan-trip-panel');panel.innerHTML=shell();renderPlanner=renderNewPlanner;bindShell();renderNewPlanner();window.TCShared?.subscribe?.(SHARED_KEY,v=>{meta=normalizeMeta(v);localStorage.setItem(META_KEY,JSON.stringify(meta));renderNewPlanner();});hydrateMeta();document.addEventListener('tc-ratings-changed',renderNewPlanner);window.TCPlanTrip={render:renderNewPlanner,meta:()=>copy(meta),zones:()=>ZONES.map(z=>({id:z.id,name:z.name,area:z.area,minutes:z.minutes}))};return true;}
  let tries=0;const timer=setInterval(()=>{tries++;if(init()||tries>160)clearInterval(timer);},50);
})();
